name: Build via Cloud Runner
run-name: ${{ github.actor }} is running CI tests via CloudRunner 🚀
on:
  workflow_dispatch:

jobs:
  runTests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - Unity
        unityVersion:
          - 2021.3.22f1
        targetPlatform:
          - Android

    steps:
      - name: Checkout (default)
        uses: actions/checkout@v3
        with:
          lfs: false

      # Cache
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - uses: game-ci/unity-builder@cloud-runner-develop
        id: aws-fargate-unity-build
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          providerStrategy: aws
          awsStackName: tatsuki5820iso-test-game-ci-20230531
          versioning: Tag
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          gitPrivateToken: ${{ secrets.GITHUB_TOKEN }}
          # You may want to export your builds somewhere external so you can access it:
          containerHookFiles: aws-s3-upload-build
